### ISSUE TITLE
Failed to connect: \"config.brokers\" threw: brokers is not a function

### ISSUE THREAD

**Issue by alannaidon** [tulios/kafkajs#1051]
Hi! I was wondering if you guys could help me understand the schema and solve this issue.  

I have a prototype with the following `docker-compose` (here is the consumer code aswell) 
```
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```  
I run `docker-compose up` and it's working fine.  

Now I have an AdonisJS project and I'm trying to make it communicate with another PROJECT (for now, my prototype) 

I run `npm install kafkajs` (`"kafkajs": "^1.15.0",`)  
Then in my Controller:
```
const { Kafka } = require('kafkajs')
async testKafka ({ request, response }) {
   const kafka = new Kafka({
      clientId: 'api-producer',
      brokers: 'localhost:9092' // Also tried to change to same as composer file 'kafka:9092'
   })
}   

const producer = kafka.producer()
request.producer = producer
await request.producer.connect() // ERROR HERE
```  

When I try to make the request using _insomnia_ I get the following ERROR:
```
{
  "error": {
    "message": "Failed to connect: \"config.brokers\" threw: brokers is not a function",
    "status": 500
  }
}
```  

It was working when I was doing both consumer/producer on the same space LIKE: 

```
/kafka // Main Folder
  /api/src   //API Code
  /microservice/src //simulating consumer
```  

But now that I'm trying to connect them from a real project it's not working.  

Also, am I right to think like: 

- I'll have a server running Kafka
- I'll have project A -- Producer
- I'll have project B -- Consumer
- Whenever I run an http request from project A and trigger kafka code **sending a message**, KAFKA server will receive this and send the message to ==> Project B (as long as it is listening to the same `topic`?.  
I read [documentation](https://kafka.js.org/docs/getting-started), but this part still blurry to me.

Thanks 

-------- **EDIT**
I was reading Kafka files and `brokers`  MUST BE an Array. My bad!

Although, if you guys could help me with the second question =)
