### ISSUE TITLE
KafkaJS + Strimzi K8S Kafka + TS React [Local Development Setup]

### ISSUE THREAD

**Issue by Thelin90** [tulios/kafkajs#1251]
@Nevon 

**Describe the bug**

Currently exploring `KafkaJS` to feed a realtime dashboard in `typescript`. And `KafkaJS` can't seem to be able to connect to my local `k8s` kafka, but I have verified nothing is wrong with my connection to my `k8s` kafka, it works as expected when verified via the console.

I followed this page: https://kafka.js.org/docs/consumer-example

Setup is:

* strimzi kafka in k8s (docker-desktop)
* KafkaJS consume example locally
* Installing via `yarn` 

**To Reproduce**

Setup a `local` kafka in `k8s` which looks like:

```bash
kubectl create namespace kafka
kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka
```

Then:
```bash
kubectl apply -f local-kafka.yaml
```

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: local-kafka
  namespace: kafka
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        type: nodeport
        port: 9093
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: localhost
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

This will create a `svc` with a random `NodePort`, in this case: `31659`.

```bash
kubectl get svc -n kafka
```

```yaml
NAME                                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)
local-kafka-kafka-external-bootstrap   NodePort    10.x.y.z.w            <none>             9093:31659/TCP
```

Currently a topic named `topic` exists in this cluster, the name is not relevant. 

I can consume the data from the topic, accessing the cluster running in `k8s` with:

`vanilla kafka distribution` [WORKS]:

```bash
bin/kafka-console-consumer.sh --bootstrap-server localhost:31659 --topic topic --from-beginning
```

Or with `kafkacat` [WORKS]:

```bash
kafkacat -b localhost:31659 -t topic -C
```

So far so good!

I have written a small piece of code, which I run from my machine, and want to access the topic data for testing, just like I do above:

```javascript
export const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['localhost:31659'],
  logLevel: logLevel.INFO
})

const consumer = kafka.consumer({ groupId: "test-group"})

const run = async () => {

  await consumer.connect();
  await consumer.subscribe({ topic: "topic", fromBeginning: true });

  await consumer.run({
    eachMessage: async ({ topic, partition, message } : { topic: string, partition: string, message: any}) => {
      console.log("Received: ", {
        partition,
        offset: message.offset,
        value: message.value.toString(),
      });
    },
  });
};
run().catch(e => console.error(`[example/consumer] ${e.message}`, e))
```

I execute this with:

```bash
yarn start
```

Logs from `console`:

![image](https://user-images.githubusercontent.com/19892351/145723107-73b71bd2-4e59-4913-9f04-ff2fe4c03bb2.png)

```bash
"logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Failed to connect: net.connect is not a function","retryCount":5,"retryTime":9440}
```

```bash
index.js:1 [example/consumer] Failed to connect: net.connect is not a function KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Failed to connect: net.connect is not a function
    at connection.js:195
    at new Promise (<anonymous>)
    at Connection.connect (connection.js:111)
    at Broker.connect (index.js:91)
    at async brokerPool.js:90
    at async Cluster.connect (index.js:109)
    at async Object.connect (index.js:134)
    at async run (Metrics.ts:15)
```

I have tried to google around on this, but it mainly seem to be an issue for others that their brokers are not available, I have verified and tested this is not the case for me, I can access it from my local machine towards my local k8s, no issue at all.

**Expected behavior**

I would expect this to simply print out the data in the console.

**Observed behavior**

I seem to keep getting: 

```bash
net.connect is not a function KafkaJSNonRetriableError
```

Which seems a bit odd? Since it is part of `node` and not `KafkaJS` from my understanding.

**Environment:**
 - OS [Mac OS 10.15.7]
 - Typescript version [^4.1.2]
 - React version [^17.0.0]
 - KafkaJS version [1.15.0]
 - Kafka version [2.8.0]
 - NodeJS version [v16.8.0]
 - Browser [Google Chrome Version 96.0.4664.93 (Official Build) (x86_64)]
 - docker-desktop version [3.3.3 (64133), engine 20.10.6, Notary: 0.6.1, Compose: 1.29.1, Credential Helper: 0.6.3, Kubernetes: v1.19.7, Snyk: v1.563.0]
 - Yarn version [1.22.11]
 
 Full `package.json` 
 
 ```yaml
 {
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/charts": "^1.2.10",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "antd": "^4.16.13",
    "kafkajs": "1.15.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Additional context**

I am not a `TypeScript` or `JS` coder, so bare with me, I am a data engineer day to day (familiar with Scala, Python) so this is a new area that I am playing around with on my free time, but I am not sure what I am doing wrong here?
