### ISSUE TITLE
AdminClient doesn't use same broker list

### ISSUE THREAD

**Issue by leandroluk** [tulios/kafkajs#1722]
I'm have a different port configured to kafka broker (port: 29002) because I'm using another kafka for another project in this port. When configure a minimal config and try to list topics using admin client I'll receive an error where the broker port is different:

![image](https://github.com/user-attachments/assets/e4b281ce-843d-4cb9-bd97-45997d5dd9d2)

**To Reproduce**

1. Start kafka using port 29002 with this `docker-compose.yml` like this
    ```yaml
    name: "example"
    networks:
      example:
        name: "example"
    services:
      example-kafka:
        image: "apache/kafka:3.9.0" # <-- this is the latest image version today
        hostname: "kafka"
        container_name: "example-kafka"
        networks: [ "example" ]
        ports: [ "29002:9092" ] # <-- this is necessary
        environment:
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_NODE_ID: 1
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
          KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19002,DOCKER://0.0.0.0:29002,CONTROLLER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9002,INTERNAL://kafka:19002,DOCKER://host.docker.internal:29002
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_LOG_DIRS: /var/lib/kafka/data
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_MIN_INSYNC_REPLICAS: 1
          KAFKA_JMX_PORT: 9003
          KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    ```
  
2. Create a `test.js` like this:
    ```js
    const { Kafka } = require('kafkajs');
    async function main() {
      const kafka = new Kafka({ clientId: 'clientId', brokers: ['localhost:29002'] });
      const admin = kafka.admin();
      await admin.connect();
      console.log(await admin.listTopics());
    }
    main()
    ```

3. Run the `test.js` file

    ```sh
    $ node ./test.js
    ```

**Expected behavior**
Are expected to print a array in console.log line but the error throws.

**Observed behavior**
If you change the kafka port to 9002, the code works.

**Environment:**
 - OS: Windows 11 version 23H2
 - KafkaJS version 2.2.4
 - Kafka version 3.9.0 (latest docker image)
 - NodeJS version 20.17.0
