### ISSUE TITLE
can't connect to broker

### ISSUE THREAD

**Issue by crapthings** [tulios/kafkajs#479]
i just copied the code from readme.md

and change the broker address to localhost:9092

but why the server address like this ?

broker":"f43be2dafb3b:9092",

btw i use this one to start kafka
https://hub.docker.com/r/bitnami/kafka

```
{"level":"ERROR","timestamp":"2019-08-23T07:15:04.982Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:04.984Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":0,"retryTime":314}
{"level":"ERROR","timestamp":"2019-08-23T07:15:05.304Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:05.304Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":1,"retryTime":604}
{"level":"ERROR","timestamp":"2019-08-23T07:15:05.911Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:05.911Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":2,"retryTime":1138}
{"level":"ERROR","timestamp":"2019-08-23T07:15:07.055Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:07.055Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":3,"retryTime":2218}
{"level":"ERROR","timestamp":"2019-08-23T07:15:09.278Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:09.278Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":4,"retryTime":4694}
{"level":"ERROR","timestamp":"2019-08-23T07:15:13.975Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","broker":"f43be2dafb3b:9092","clientId":"my-app","stack":"Error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"}
{"level":"ERROR","timestamp":"2019-08-23T07:15:13.975Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":5,"retryTime":10562}
{"level":"ERROR","timestamp":"2019-08-23T07:15:13.977Z","logger":"kafkajs","message":"[Producer] Connection error: getaddrinfo ENOTFOUND f43be2dafb3b f43be2dafb3b:9092","retryCount":0,"retryTime":340}
```

```yaml
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
```

```js
const { Kafka } = require('kafkajs')

const kafka = new Kafka({
  clientId: 'my-app',
  brokers: 'localhost:9092',
})

const producer = kafka.producer()
const consumer = kafka.consumer({ groupId: 'test-group' })

const run = async () => {
  // Producing
  await producer.connect()
  await producer.send({
    topic: 'test-topic',
    messages: [
      { value: 'Hello KafkaJS user!' },
    ],
  })

  // Consuming
  await consumer.connect()
  await consumer.subscribe({ topic: 'test-topic', fromBeginning: true })

  await consumer.run({
    eachMessage: async ({ topic, partition, message }) => {
      console.log({
        partition,
        offset: message.offset,
        value: message.value.toString(),
      })
    },
  })
}

run().catch(console.error)
```

**Comment by tulios** [comment]
Hi @crapthings, your setup is advertising the docker hostnames. Kafka has a configuration for that, so it can correctly pick up the host IP. Try setting the `KAFKA_ADVERTISED_HOST_NAME` to the host IP.

**Comment by crapthings** [comment]
for now i can make the example code working with the docker-compose file from this repo.

https://github.com/tulios/kafkajs/blob/master/docker-compose.2_2.yml

![image](https://user-images.githubusercontent.com/1147704/63581268-40eec900-c5c9-11e9-9a4c-a800f27c1b70.png)


but why it takes such long time to receive message?

**Comment by tulios** [comment]
The consumer was rebalancing, so I guess that the group was already active when this instance joined. It's fast if it's a stable group. Maybe you had previous attempts and the consumer never properly left the group.

**Comment by angelsvirkov** [comment]
@tulios , I am getting the same problem.

I provide a host and IP as `brokers` in the config but then I get the error `getaddrinfo ENOTFOUND <someDomain.com>`. Would you please elaborate on what you actually are doing? Are you replacing the brokers? I also saw that in another issue #453. I am not sure it is related but it really seems that you are trying to pick another broker.

The way I connect to the brokers works when I use other packages (e.g. `kafka-node`). So I assume that the problem is not in the configuration of the broker itself.

Or maybe you are doing this broker replacement for a good reason. If that is the case would you please explain what and why you are doing it. Maybe also mentioning it in the docs would help.

**Comment by tgbv** [comment]
If it helps anyone, I received the same error and I managed to solve it by providing the hostname to kafka service in `docker-compose.yml`:
```yml
kafka:
  image: 'bitnami/kafka:2'
  hostname: localhost
  ports:
    - '9092:9092'
  volumes:
    - 'kafka_data:/bitnami'
  environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
  depends_on:
    - zookeeper
```
