### ISSUE TITLE
docker connectivity problem

### ISSUE THREAD

**Issue by oemergenc** [tulios/kafkajs#803]
**Describe the bug**
Hi, 

i am experiencing problems while trying to access a kafka broker from my kafka consumer when running in the same docker setup. Manually connecting to the kafka broker from inside the container works, so i believe the containers are running fine.
However, trying to access the kafka broker with my kafkajs consumer does not work. The problem only occurs when running inside docker.

Here is my docker file:
```
version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "my-topic:1:1"

  my-kafkajs-consumer-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - 3149:3149
    environment:
      - KAFKA_BROKER_ADDRESS_LIST=kafka:9093
```
After running `docker-compose up` i got the following error message:
```
[ServerKafka] ERROR [Connection] Response Metadata(key: 3, version: 5) {"timestamp":"2020-07-02T05:02:02.145Z","logger":"kafkajs","broker":"kafka:9093","clientId":"  my-kafkajs-consumer-app-server","error":"This server does not host this topic-partition","correlationId":2,"size":147}
```

However executing the following from inside a running `  my-kafkajs-consumer-app` container succeeds:

```
root@8395504eae10:/usr/src/app# kafkacat -b kafka:9093 -L
Metadata for all topics (from broker 1001: kafka:9093/1001):
 1 brokers:
  broker 1001 at kafka:9093
 2 topics:
  topic "my-topic" with 1 partitions:
    partition 0, leader 1001, replicas: 1001, isrs: 1001
```

Any ideas what could be the problem here, i guess it is related to some networking issues. Using this docker setup for some java services seems to work.
