### ISSUE TITLE
Cant connect to kafka

### ISSUE THREAD

**Issue by CarterScadden** [tulios/kafkajs#837]
my `KAFKA_ADVERTISED_HOST_NAME` is not being set correctly I believe. the problem us when going through the setup documentation and running:

`export HOST_IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)`

Does seem to work on my ubuntu 20.04

and running: `$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)`
returns `172.18.0.1: command not found`

Help getting connected would be greatly appreciated

The errors:
```
"level":"ERROR","timestamp":"2020-08-14T15:49:53.961Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo EAI_AGAIN kafka2","broker":"kafka2:9092","clientId":"my-app","stack":"Error: getaddrinfo EAI_AGAIN kafka2\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
{"level":"ERROR","timestamp":"2020-08-14T15:49:53.962Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: getaddrinfo EAI_AGAIN kafka2","retryCount":0,"retryTime":319}
{"level":"ERROR","timestamp":"2020-08-14T15:49:54.286Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo EAI_AGAIN kafka1","broker":"kafka1:9092","clientId":"my-app","stack":"Error: getaddrinfo EAI_AGAIN kafka1\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
{"level":"ERROR","timestamp":"2020-08-14T15:49:54.287Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: getaddrinfo EAI_AGAIN kafka1","retryCount":1,"retryTime":676}
{"level":"ERROR","timestamp":"2020-08-14T15:49:54.967Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo EAI_AGAIN kafka2","broker":"kafka2:9092","clientId":"my-app","stack":"Error: getaddrinfo EAI_AGAIN kafka2\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
{"level":"ERROR","timestamp":"2020-08-14T15:49:54.968Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: getaddrinfo EAI_AGAIN kafka2","retryCount":2,"retryTime":1426}
```

My docker looks like this:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # the redis configuration
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
```
