### ISSUE TITLE
kafkajs terminates whole program when manually shutting down one broker

### ISSUE THREAD

**Issue by gonejack** [tulios/kafkajs#939]
kafkajs terminates whole program after manually shutting down one broker by `docker stop kafka2` in this test. developers has no chance to handle this error.

docker-compose.yaml, remember to replace all 192.168.9.27
```
version: '2'
services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.9.27                     
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.9.27:9092   
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    container_name: kafka1
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.9.27                    
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.9.27:9093   
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    container_name: kafka2
  kafka-manager:
    image: sheepkiller/kafka-manager            
    environment:
      ZK_HOSTS: 192.168.9.27                   
    ports:
      - "9000:9000"

```

consumer_js.ts
```typescript
import {Kafka, Consumer, EachMessagePayload} from 'kafkajs'

const logger = console

class slot<T> {
    private need: Promise<T>
    private needResolve: Function
    private offer: T
    private offerResolve: Function
    async get(): Promise<T> {
        if (this.offer) {
            const data = this.offer
            this.offerResolve()
            this.offer = null
            return data
        } else {
            this.need = new Promise<T>(res => {
                this.needResolve = res
            })
            return this.need
        }
    }
    async set(data: T): Promise<void> {
        if (this.need) {
            this.needResolve(data)
            this.need = null
        } else {
            const offer = new Promise<T>(res => {
                this.offer = data
                this.offerResolve = res
            })
            await offer
        }
    }
}

export class MyConsumer {
    private consumer: Consumer
    private stopped: boolean
    private crashed: boolean
    private slot = new slot<EachMessagePayload>()
    constructor() {
        const kafka = new Kafka({
            clientId: 'my-app',
            brokers:  ['127.0.0.1:9092', '127.0.0.1:9093'],
        })
        this.consumer = kafka.consumer({groupId: "test-group"})
        this.consumer.on(this.consumer.events.GROUP_JOIN, logger.info)
        this.consumer.on(this.consumer.events.CONNECT, logger.info)
        this.consumer.on(this.consumer.events.DISCONNECT, logger.info)
        this.consumer.on(this.consumer.events.STOP, (msg) => {
            logger.info(msg)
            this.stopped = true
        })
        this.consumer.on(this.consumer.events.CRASH, (msg) => {
            logger.info(msg)
            this.crashed = true
        })
    }
    async start() {
        await this.consumer.connect()
        await this.consumer.subscribe({topic: "test"})
        await this.consumer.run({eachMessage: async payload => await this.slot.set(payload)})
    }
    async stop() {
        await this.consumer.stop()
    }
    async next() {
        if (this.crashed || this.stopped) {
            await this.stop()
            return false
        }
        return true
    }
    async consume() {
        const payload = await this.slot.get()
        return payload.message.value.toString()
    }
    error() {
        if (this.crashed) {
            return new Error("crashed")
        }
        return null
    }
}
```

consumer_js_test.ts
```typescript
import {MyConsumer} from "./consumer_js";
import {sleep, time} from "../time/time";

const logger = console

async function testConsumer() {
    let consumer = new MyConsumer()

    logger.info("starting")
    await consumer.start()
    logger.info("start finished")

    while (await consumer.next()) {
        const message = await consumer.consume()
        logger.info("got: %s", message)
    }

    logger.info("error: %O", consumer.error())
    await sleep(time.minute * 10)

    logger.info("stopping")
    await consumer.stop()
    logger.info("stop finished")
}

testConsumer()
```

**Environment:**
 - OS: 10.15.7
 - KafkaJS version 1.14.0
 - Kafka version 2.6.0
 - NodeJS v14.12.0
